### ISSUE TITLE
我想问一下 是怎么定位到diy的目录的

### ISSUE THREAD

**Issue by hyird** [ljk4160/GDOCK#9]

**Comment by hyird** [comment]
我看 每次定位文件  ../../../  ../   ../../   我都很迷  不都是在项目的根目录的 怎么 路径还不一样了

**Comment by ljk4160** [comment]
只要把源码包放到diy目录下会自动集成.把集成的包添加到config就行

**Comment by ljk4160** [comment]
参考示例,添加qntfs,并且gdockfull128.config里添加了CONFIG_PACKAGE_kmod-fs-qntfs=y,生成的固件就集成了qntfs

**Comment by hyird** [comment]
> 参考示例,添加qntfs,并且gdockfull128.config里添加了CONFIG_PACKAGE_kmod-fs-qntfs=y,生成的固件就集成了qntfs
这个我知道  我是想替换 源码的文件 不是添加包   你那个 我看每次 路径都不一样 所以就很迷

**Comment by ljk4160** [comment]
../是相对路径的上级目录,修改文件根据你实际情况看你改什么文件
diy.sh所在目录就是根目录的lede下(lean源码)

**Comment by hyird** [comment]
> ../是相对路径的上级目录,修改文件根据你实际情况看你改什么文件
> diy.sh所在目录就是根目录的lede下(lean源码)

echo '删除旧版argon,链接新版'
rm -rf ./package/lean/luci-theme-argon
ln -s ../../../diy/luci-theme-argon ./package/lean/
这个为啥三个../  rm-rf 会把当前路径 弄过去么
echo '修改banner'
rm -rf package/base-files/files/etc/banner
cp -f ../banner package/base-files/files/etc/
这个 又迷惑了  banner 和diy.sh 是同目录下   删除默认banner 这是在lede源码根目录下吧  ../banner 又是上层目录  diy.sh 又和 banner同目录  diy.sh和lede这个文件夹（源码） 是在同一级目录下的吧

**Comment by ljk4160** [comment]
banner放在项目根目录,你当前在lede下,所以删除直接用pac..../banner,
拷贝当然要返回上级目录才能读到所以是../banner

**Comment by hyird** [comment]
> banner放在项目根目录,你当前在lede下,所以删除直接用pac..../banner,
> 拷贝当然要返回上级目录才能读到所以是../banner

那 ln -s argon的那个主题的是什么原因了  ../../../

**Comment by ljk4160** [comment]
echo '删除旧版argon,链接新版'
rm -rf ./package/lean/luci-theme-argon
ln -s ../../../luci-theme-argon ./package/lean/

删除原来的包这个没什么可说,
软链接是相对路径,相对./package/lean/luci-theme-argon来说,项目下的luci-theme-argon就是要返回3次上级目录才能到达luci-theme-argon

**Comment by hyird** [comment]
> gon ./package/lean/

明白了 感谢  还有 最后一个问题   diy.sh是在  lede目录下的      banner 和diy.sh又在项目的根目录 
但是为什么 banner 文件 跑到 lede文件夹的 上一级目录里面去了

**Comment by ljk4160** [comment]
在actions里运行脚本是../diy.sh,所以对脚本来说他的当前路径应该是lede下

**Comment by hyird** [comment]
又看了下  明白了 是在 lede 目录下面 执行的../diy.sh

**Comment by hyird** [comment]
打扰了 感谢   这个 有点绕。。
